# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: required
dist: trusty

python:
  - 3.7
virtualenv:
    system_site_package: true
before_install:
 - sudo apt-get update
 - sudo apt-get install -qq python3-numpy
 - sudo pip3 install matplotlib
script:
  - python -m example1_test.py

notifications:
  email:
    - daniel.materka+backprop@gmail.com