# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: required
dist: trusty

python:
  - 2.7
  - 3.4
virtualenv:
    system_site_package: true
before_install:
 - sudo apt-get update
 - sudo apt-get install -qq python-numpy
script:
# - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest discover; fi
# - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest discover; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then python -m example1.py; fi

notifications:
  email:
    - daniel.materka+backprop@gmail.com