# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: required
dist: trusty

python:
  - 3.4
virtualenv:
    system_site_package: true
before_install:
 - sudo apt-get update
 - sudo apt-get install -qq python3-numpy
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then python -m unittest discover; fi

notifications:
  email:
    - daniel.materka+backprop@gmail.com