# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: required
dist: bionic

python:
  - 3.8
virtualenv:
    system_site_package: true
before_install:
 - sudo apt-get update
 - sudo apt-get install -qq g++ libfreetype6-dev
 - sudo pip install -r requirements.txt
script:
  - python -m unittest discover -p "Test*"

notifications:
  email:
    - daniel.materka+backprop@gmail.com